package com.carboexco.moduloProyectos.controller;

import com.carboexco.moduloProyectos.entity.Proyecto;
import com.carboexco.moduloProyectos.entity.ProyectoPersona;
import com.carboexco.moduloProyectos.repository.ProyectoPersonaRepository;
import com.carboexco.moduloProyectos.repository.ProyectoRepository;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.ArrayList;

@CrossOrigin(origins = "*", allowedHeaders = "*")
@RestController
@RequestMapping("/generador")
public class GeneradorPdf {
    private static String FILE = "c:/img/img/Informeproyecto.pdf";
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    private static Font small = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL);

    private Proyecto proyecto;
    @Autowired
    ProyectoRepository proyectoRepository;
    @Autowired
    private ProyectoPersonaRepository proyectoPersonaRepository;

    @GetMapping("/pdf/{id}")
    public String genearPdf(@PathVariable int id) throws FileNotFoundException, DocumentException {

            Optional<Proyecto> nuevo = proyectoRepository.findById(id);

            if (nuevo.isPresent()) {
                this.proyecto = nuevo.get();
                Document document = new Document();
                PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(FILE));
                Header header = new Header();
                writer.setPageEvent(header);
                float headerHeight = 50;
                float contentMarginTop = 36;
                float contentMarginBottom = 36;
                document.setMargins(36, 36 + headerHeight, 36 + contentMarginTop, 36 + contentMarginBottom);
                document.open();
                addMetaData(document);
                addTitlePage(document);
                addContent(document);
                document.close();
                return "generado exitosamente";
            } else {
                throw new NullPointerException();
            }

    }

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    private static void addMetaData(Document document) {
        document.addTitle("Informe de proyeto");
        document.addSubject("Informe de proyecto: "+ "NOMBRE DE PROYECTO");
        document.addKeywords("Carboexco, Informe, Modulo de proyectos");
        document.addAuthor("Carboexco");
        document.addCreator("Lars Vogel");
    }

    private static void addTitlePage(Document document) throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 3);
        // Lets write a big header
        preface.add(new Paragraph("Informe de proyeto", catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Reporte generado por: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph(
                "informe de prueba generado par o computadora",
                smallBold));

        addEmptyLine(preface, 8);

        preface.add(new Paragraph(
                "la informacion vista en este documento no es real esto es un bosquejo.",
                redFont));

        document.add(preface);
        // Start a new page
        document.newPage();
    }

    private void addContent(Document document) throws DocumentException {
        Paragraph encabezado = new Paragraph();
        addEmptyLine(encabezado, 3);

        Anchor anchor = new Anchor("Indicé informe de proyecto "+ this.proyecto.getNombreProyecto(), catFont);
        anchor.setName("Indicé informe de proyecto "+ this.proyecto.getNombreProyecto());// TITULO DE LA HOJA

        // Second parameter is the number of the chapter
        Paragraph inicial=new Paragraph(encabezado);
        inicial.add(anchor);
        Chapter catPart = new Chapter(inicial, 1);
        Paragraph paragraph = new Paragraph();
        addEmptyLine(paragraph, 1);
        Paragraph subPara = new Paragraph("Información del proyecto", subFont);
        Section subCatPart = catPart.addSection(subPara);
        // add a list
        createList(subCatPart);
        //Paragraph paragraph = new Paragraph();
        subCatPart.add(paragraph);

        // add a table
        createTable(subCatPart);

        // now add all this to the document
        document.add(catPart);

        // Next section
        int n =1;
        anchor = new Anchor("Informe de proyeto", catFont);// Subtitulo
        anchor.setName("Informe de proyeto");
        catPart = new Chapter(new Paragraph(anchor), n++);
        Paragraph preface = new Paragraph();
        addEmptyLine(preface, 1); //LINEA EN BLANCO
        ArrayList<ProyectoPersona> proyectoPersona= (ArrayList<ProyectoPersona>) proyectoPersonaRepository.findById_Proyecto(proyecto.getId());
        String responsables = proyectoPersona.stream()
                .map(pp -> String.valueOf(pp.getId().getPersona()))
                .distinct()
                .collect(Collectors.joining(", ")); //RESPONSABLES DEL PROYECTO
        preface.add(new Paragraph(
                "Proyecto "+proyecto.getIdTipoProyecto().getNombre()+" #"+ proyecto.getId()+ " "
                        +proyecto.getNombreProyecto()+" de prioridad "+proyecto.getIdPrioridad().getNombrePrioridad()+
                        ", responsables del proyecto "+responsables+"."
                ,small)); //PARRAFO INFORMACION DEL PROYECTO
        addEmptyLine(preface,1); //LINEA EN BLANCO
        catPart.add(preface); //AGREGAR PARRAFO AL DOCUMENTO

        if(this.proyecto.getDescripcionProyecto()!=null){

            subPara = new Paragraph("Descripción del proyecto", subFont);//SUBTITULO
            subCatPart = catPart.addSection(subPara);
            subCatPart.add(new Paragraph(this.proyecto.getDescripcionProyecto())); //INFORMACION DESCRIPCION
            subCatPart.add(paragraph);
        }
        if(proyecto.getJustificacion()!=null){
            subPara = new Paragraph("Justificación del proyecto", subFont);//SUBTITULO
            subCatPart = catPart.addSection(subPara);
            subCatPart.add(new Paragraph(this.proyecto.getJustificacion()));//INFORMACION DESCRIPCION
            subCatPart.add(paragraph);
        }
        if(proyecto.getObjetivoGeneral()!=null){

            subPara = new Paragraph("Objetivo general del proyecto", subFont);//SUBTITULO
            subCatPart = catPart.addSection(subPara);
            subCatPart.add(new Paragraph(this.proyecto.getObjetivoGeneral()));//INFORMACION DESCRIPCION
            subCatPart.add(paragraph);
        }
        if(proyecto.getObjetivoEspecifico()!=null){

            subPara = new Paragraph("Objetivo especifico del proyecto", subFont);//SUBTITULO
            subCatPart = catPart.addSection(subPara);
            subCatPart.add(new Paragraph(this.proyecto.getObjetivoEspecifico()));//INFORMACION DESCRIPCION
            subCatPart.add(paragraph);
        }

        // now add all this to the document
        document.add(catPart); //AGREGAR DATOS AL DOCUMENTO
    }

    private static void createTable(Section subCatPart)
            throws BadElementException {
        PdfPTable table = new PdfPTable(3);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Table Header 1"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 2"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 3"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        table.addCell("1.0");
        table.addCell("1.1");
        table.addCell("1.2");
        table.addCell("2.1");
        table.addCell("2.2");
        table.addCell("2.3");

        subCatPart.add(table);

    }

    private void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        if(this.proyecto.getDescripcionProyecto()!=null){
            list.add(new ListItem("Descripción del proyecto"));
        }
        if(proyecto.getJustificacion()!=null){
            list.add(new ListItem("Justificación del proyecto"));
        }
        if(proyecto.getObjetivoGeneral()!=null){
            list.add(new ListItem("Objetivo general del proyecto"));
        }
        if(proyecto.getObjetivoEspecifico()!=null){
            list.add(new ListItem("Objetivo especifico del proyecto"));
        }

        subCatPart.add(list);
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    };
}
